from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from tradinglab.config import (  # noqa: F401
    START_DATE,
    END_DATE,
    INITIAL_CAPITAL,
    SHORT_WINDOW,
    LONG_WINDOW,
    MIN_VOL20,
    FEE_RATE,
    SLIPPAGE_RATE,
    SLIPPAGE_MODE,
    SLIPPAGE_BPS_BASE,
    SLIPPAGE_BPS_PER_TURNOVER,
    REBALANCE,
    MOM_LOOKBACK,
    TOP_N,
    REGIME_SYMBOL,
    ALLOW_REGIME_TRADE,
    EXECUTION,
    PRICE_MODE,
    MAX_POSITION_WEIGHT,
    MAX_SECTOR_WEIGHT,
    MAX_TURNOVER_PER_REBALANCE,
    MAX_GROSS_EXPOSURE,
    CASH_BUFFER,
    MAX_ORDER_NOTIONAL,
    MAX_ORDERS_PER_RUN,
    TRAILING_STOP_PCT,
    TIME_STOP_DAYS,
    TARGET_VOL,
    VOL_LOOKBACK,
    DATA_DIR,
    RESULTS_DIR,
)

__all__ = [
    "START_DATE",
    "END_DATE",
    "INITIAL_CAPITAL",
    "SHORT_WINDOW",
    "LONG_WINDOW",
    "MIN_VOL20",
    "FEE_RATE",
    "SLIPPAGE_RATE",
    "SLIPPAGE_MODE",
    "SLIPPAGE_BPS_BASE",
    "SLIPPAGE_BPS_PER_TURNOVER",
    "REBALANCE",
    "MOM_LOOKBACK",
    "TOP_N",
    "REGIME_SYMBOL",
    "ALLOW_REGIME_TRADE",
    "EXECUTION",
    "PRICE_MODE",
    "MAX_POSITION_WEIGHT",
    "MAX_SECTOR_WEIGHT",
    "MAX_TURNOVER_PER_REBALANCE",
    "MAX_GROSS_EXPOSURE",
    "CASH_BUFFER",
    "MAX_ORDER_NOTIONAL",
    "MAX_ORDERS_PER_RUN",
    "TRAILING_STOP_PCT",
    "TIME_STOP_DAYS",
    "TARGET_VOL",
    "VOL_LOOKBACK",
    "DATA_DIR",
    "RESULTS_DIR",
]
